name: Publish to Nexus

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted,services]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0s

    - name: Configure AWS credentials - ${{ env.POOL_NAME }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/${{ env.POOL_NAME }}-k8s-service-account-github-actions-runner
        role-session-name: ${{ github.run_id }}
        role-duration-seconds: 3600

    - name: Get nexus password from aws ssm
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/services/eks/nexus/ghar_token"
        env_variable_name: "NEXUS_TOKEN"    

    - name: build evaluator.dagger
      run: mvn package --file evaluator.dagger/pom.xml

    - name: publish to nexus
      run: curl -u github:$NEXUS_TOKEN --upload-file evaluator.dagger/evaluator.dagger-2.6.0-SNAPSHOT.jar https://nexus.services.bwell.zone/repository/bwell/
